apiVersion: apps/v1
kind: Deployment
metadata:
  name: rds-deployment  
  labels:
    app: rds
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rds
  template:
    metadata:
      labels:
        app: rds
    spec:
      containers:
        - name: rds
          image: gowthamg404/user-management:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: rds
spec:
  selector:
    app: rds
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
